spring:
    jackson:
      default-property-inclusion: non_null
    datasource:
      name: test
      url: jdbc:mysql://localhost:3306/supermarket?characterEncoding=utf8&useSSL=false
      username: root
      password: 123
      driverClassName: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5
    redis:
      host: 127.0.0.1
      port: 6379
      password: 12345
      poolMaxTotal : 1000
      poolMaxIdle : 500
      poolMaxWait : 500
      timeout: 20

      resources:
            add-mappings: true
            chain:
              cache: true
              enabled: true
              gzipped: true
              html-application-cache: true
            static-locations: classpath:/
            cache:
              period: 3600ms


mybatis:
    #Mybatis扫描
    mapper-locations: classpath*:mapper/*.xml
    #起别名。可省略写mybatis的xml中的resultType的全路径
    type-aliases-package: com.scau.kevin.supermarket.entity


server:
  port: 8080
logging:
  level:
    com.scau.kevin.supermarket.dao.*: debug




